"""Generate the Rill project from the semantic registry.

The ``rill/`` project is a local exploration mirror of the governed semantic
layer. Its models select from the ``semantic_*`` views published inside the
analytics snapshot, and its metrics views repeat the registry's dimensions
and measures verbatim -- so Rill can never drift from the application. Run
after changing ``api/semantic_layer.py``:

    python scripts/generate_rill_project.py

A parity test asserts the committed files match the generator's output.
"""

from __future__ import annotations

from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from api.semantic_layer import SEMANTIC_MODELS  # noqa: E402

ROOT = Path(__file__).resolve().parents[1] / "rill"

_FORMAT_PRESETS = {"currency": "currency_usd", "percent": "percentage"}

_HEADER = "# Generated by scripts/generate_rill_project.py -- do not edit.\n"


def model_yaml(name: str) -> str:
    return (
        f"{_HEADER}"
        "type: model\n"
        "connector: duckdb\n"
        "materialize: true\n"
        "sql: |\n"
        f"  SELECT * FROM flux.semantic_{name}\n"
    )


def metrics_yaml(model) -> str:
    lines = [
        _HEADER,
        "version: 1",
        "type: metrics_view",
        f"display_name: Flux {model.display_name.lower()}",
        f"model: flux_{model.name}",
    ]
    if model.time_column:
        lines.append(f"timeseries: {model.time_column}")
    lines.append("")
    lines.append("dimensions:")
    for dimension in model.dimensions:
        lines.append(f"  - name: {dimension.name}")
        lines.append(f"    column: {dimension.name}")
        if dimension.description:
            lines.append(f"    description: {dimension.description}")
    lines.append("")
    lines.append("measures:")
    for measure in model.measures:
        lines.append(f"  - name: {measure.name}")
        lines.append(f"    expression: {measure.expression}")
        if measure.description:
            lines.append(f"    description: {measure.description}")
        preset = _FORMAT_PRESETS.get(measure.format)
        if preset:
            lines.append(f"    format_preset: {preset}")
    return "\n".join(lines) + "\n"


def explore_yaml(model) -> str:
    return (
        f"{_HEADER}"
        "type: explore\n"
        f"display_name: Flux {model.display_name.lower()} explorer\n"
        f"metrics_view: flux_{model.name}_metrics\n"
        'dimensions: "*"\n'
        'measures: "*"\n'
    )


def generated_files() -> dict[Path, str]:
    files: dict[Path, str] = {}
    for model in SEMANTIC_MODELS:
        files[ROOT / "models" / f"flux_{model.name}.yaml"] = model_yaml(
            model.name
        )
        files[ROOT / "metrics" / f"flux_{model.name}_metrics.yaml"] = (
            metrics_yaml(model)
        )
        files[ROOT / "dashboards" / f"flux_{model.name}_explore.yaml"] = (
            explore_yaml(model)
        )
    return files


def main() -> None:
    files = generated_files()
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(ROOT.parent)}")
    # Remove stale generated files (renamed or deleted models) so the
    # project always mirrors the registry exactly.
    for directory in ("models", "metrics", "dashboards"):
        for path in sorted((ROOT / directory).glob("flux_*.yaml")):
            if path not in files:
                path.unlink()
                print(f"removed stale {path.relative_to(ROOT.parent)}")


if __name__ == "__main__":
    main()
